#![no_std]
#![no_main]

use aya_ebpf::macros::map;
use aya_ebpf::maps::{HashMap, RingBuf};
use anticheat_common::ProcessKey;

// Generated by `aya-tool generate task_struct > src/vmlinux.rs` (make vmlinux)
#[allow(warnings)]
#[rustfmt::skip]
mod vmlinux;

mod lsm_bpf;
mod lsm_ptrace;
mod sched_exec;

#[map]
pub static EVENTS: RingBuf = RingBuf::with_byte_size(256 * 1024, 0);

// Protected processes (tgid + start_time) -> 1u8. Registered by eBPF when it observes exec.
// start_time differs across PID reuse, so no false protection and no removal on exit.
#[map]
pub static PROTECTED_PROCS: HashMap<ProcessKey, u8> = HashMap::with_max_entries(256, 0);

// Coarse protection for the daemon itself (tgid only). Temporary until daemon lifetime is settled.
#[map]
pub static PROTECTED_TGIDS: HashMap<u32, u8> = HashMap::with_max_entries(16, 0);

// tgid of the monitor (daemon). To allow its legitimate access to protected targets
// (maps/mem scans), the ptrace hook lets the caller through if it is here.
#[map]
pub static MONITOR_TGIDS: HashMap<u32, u8> = HashMap::with_max_entries(4, 0);

// exec registration trigger + propagation. If the parent tgid is here, register the child into
// PROTECTED_PROCS and add the child tgid here too, tracking the whole subprocess tree.
#[map]
pub static WATCH_TGIDS: HashMap<u32, u8> = HashMap::with_max_entries(256, 0);

// Protected kernel link IDs -> 1u8
#[map]
pub static PROTECTED_LINKS: HashMap<u32, u8> = HashMap::with_max_entries(16, 0);

// Protected kernel prog IDs -> 1u8
#[map]
pub static PROTECTED_PROGS: HashMap<u32, u8> = HashMap::with_max_entries(16, 0);

// Protected kernel map IDs -> 1u8
#[map]
pub static PROTECTED_MAPS: HashMap<u32, u8> = HashMap::with_max_entries(16, 0);

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    unsafe { core::hint::unreachable_unchecked() }
}
