#![no_std]
#![no_main]

use aya_ebpf::helpers::bpf_ktime_get_ns;
use crate::vmlinux::task_struct;
use aya_ebpf::macros::map;
use aya_ebpf::maps::{Array, HashMap, RingBuf};
use anticheat_common::{EventHeader, MapFullEvent, ProcessKey, ProtFlags, EVENT_MAP_FULL};

// Generated by `aya-tool generate task_struct > src/vmlinux.rs` (make vmlinux)
#[allow(warnings)]
#[rustfmt::skip]
mod vmlinux;

// Adding or removing an #[lsm(hook = ...)] below means editing `shims[]` in
// kernel/ebpf_guard.c to match. That list is what the kernel module watches to
// notice a hook being detached, and a hook missing from it is a hook nothing
// guards -- detaching it takes five bytes and produces no report at all.
mod lsm_bpf;
mod lsm_mmap;
mod lsm_ptrace;
mod lsm_signal;
mod sched_exec;

#[map]
pub static EVENTS: RingBuf = RingBuf::with_byte_size(256 * 1024, 0);

// Protected processes (tgid + start_time). Registered by eBPF when it observes exec.
// start_time differs across PID reuse, so no false protection and no removal on exit.
// Entries are never removed, so capacity is consumed by cumulative execs in the game's
// process tree, not by concurrent process count. The map is preallocated, so a larger
// max_entries costs fixed memory (~400KB here) and nothing per entry; running out is the
// only real failure mode, and it is reported via EVENT_MAP_FULL.
#[map]
pub static PROTECTED_PROCS: HashMap<ProcessKey, ProtFlags> = HashMap::with_max_entries(4096, 0);

// Coarse protection for the daemon itself (tgid only). Temporary until daemon lifetime is settled.
#[map]
pub static PROTECTED_TGIDS: HashMap<u32, ProtFlags> = HashMap::with_max_entries(16, 0);

// tgid of the monitor (daemon). To allow its legitimate access to protected targets
// (maps/mem scans), the ptrace hook lets the caller through if it is here.
#[map]
pub static MONITOR_TGIDS: HashMap<u32, ProtFlags> = HashMap::with_max_entries(4, 0);

// exec registration trigger + propagation. If the parent tgid is here, register the child into
// PROTECTED_PROCS and add the child tgid here too, tracking the whole subprocess tree.
#[map]
pub static WATCH_TGIDS: HashMap<u32, ProtFlags> = HashMap::with_max_entries(4096, 0);

// Protected kernel link IDs
#[map]
pub static PROTECTED_LINKS: HashMap<u32, ProtFlags> = HashMap::with_max_entries(16, 0);

// Protected kernel prog IDs
#[map]
pub static PROTECTED_PROGS: HashMap<u32, ProtFlags> = HashMap::with_max_entries(16, 0);

// btf_ids of the bpf_lsm_* functions this anti-cheat attaches to, written by the
// loader before the bpf hook goes live.
//
// The bpf hook used to deny every BPF_PROG_TYPE_LSM load outright. That also
// took out systemd's RestrictFileSystems=, which is itself a BPF LSM program --
// and systemd treats a failed BPF load as "no BPF on this kernel" rather than an
// error, so the restriction silently stopped being enforced with nothing in the
// journal to show for it. Matching on the attach target instead denies only the
// loads aimed at hooks this anti-cheat owns.
#[map]
pub static GUARDED_ATTACH_IDS: HashMap<u32, ProtFlags> = HashMap::with_max_entries(16, 0);

// Protected kernel map IDs
#[map]
pub static PROTECTED_MAPS: HashMap<u32, ProtFlags> = HashMap::with_max_entries(16, 0);

// One flag per protection map, set after the first EVENT_MAP_FULL report for it.
// Without this, a full map emits an event on every subsequent exec and crowds real
// detections out of the ring buffer. Racy across CPUs, which at worst costs a
// duplicate report.
#[map]
pub static MAP_FULL_REPORTED: Array<u32> = Array::with_max_entries(4, 0);

// Whether a task is under protection. PROTECTED_PROCS keys on (tgid+start_time)
// so PID reuse cannot produce a false hit; PROTECTED_TGIDS is the daemon's own
// coarse protection, which is tgid-only until its lifetime is settled.
//
// Safety: caller passes a valid task_struct (PTR_TO_BTF_ID from an LSM argument
// or bpf_get_current_task_btf); the verifier rewrites the field reads into
// probe reads.
pub unsafe fn task_is_protected(task: *const task_struct) -> bool {
    if task.is_null() {
        return false;
    }

    let tgid = (*task).tgid as u32;
    if PROTECTED_TGIDS.get(&tgid).is_some() {
        return true;
    }

    let leader = if (*task).group_leader.is_null() {
        task
    } else {
        (*task).group_leader
    };

    let key = ProcessKey {
        pid: tgid,
        _pad: 0,
        start_time: (*leader).start_time,
    };

    PROTECTED_PROCS.get(&key).is_some()
}

pub fn now_ns() -> u64 {
    // Safety: bpf_ktime_get_ns is always available to LSM and tracepoint programs
    unsafe { bpf_ktime_get_ns() }
}

// Report that a protection map hit its capacity, at most once per map.
// A process that fails to register is silently unprotected, so this is the only
// signal that it happened.
pub unsafe fn report_map_full(map_id: u32, tgid: u32) {
    if let Some(flag) = MAP_FULL_REPORTED.get_ptr_mut(map_id) {
        if *flag != 0 {
            return;
        }
        *flag = 1;
    }

    if let Some(mut entry) = EVENTS.reserve::<MapFullEvent>(0) {
        // Writing the whole struct initializes the padding too, so no
        // uninitialized kernel memory reaches userspace
        entry.write(MapFullEvent {
            header: EventHeader::new(EVENT_MAP_FULL, now_ns()),
            map_id,
            tgid,
        });
        entry.submit(0);
    }
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    unsafe { core::hint::unreachable_unchecked() }
}
